// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD2LRPL7EOQM-Z-ZpAGbKw4FygByLOfUDc",
    authDomain: "projekti-6bb4c.firebaseapp.com",
    projectId: "projekti-6bb4c",
    storageBucket: "projekti-6bb4c.firebasestorage.app",
    messagingSenderId: "584129027887",
    appId: "1:584129027887:web:5bdad06a3cd3ccac8ecbda",
    measurementId: "G-V7JSKK1MZD",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD2LRPL7EOQM-Z-ZpAGbKw4FygByLOfUDc",
    projectId: "projekti-6bb4c",
    storageBucket: "projekti-6bb4c.firebasestorage.app",
    messagingSenderId: "584129027887",
    appId: "1:584129027887:web:5bdad06a3cd3ccac8ecbda",
  );
}
